/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quote_things;

import com.google.gson.Gson;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class RenderQuotes {

    public static void main(String[] args) {

        Quotes[] quoteList = getQuotes("./assets/quotes.json");

        System.out.println(shuffleQuotes(quoteList, Math.random()));
        ;
    }

    public static Quotes[] getQuotes(String filePathString) {
        Path filePath = Paths.get(filePathString);

        Quotes[] testQuotesParse = new Quotes[]{};

        try {
            testQuotesParse = parseQuotes(filePath);
        } catch (IOException ex) {
            System.out.println("I could not read these files. Please try again.");
            ex.printStackTrace();
        }

        return testQuotesParse;
    }

    public static Quotes[] parseQuotes(Path quotesPath) throws IOException {

        String quoteFile = "";

        try (BufferedReader readQuotes = Files.newBufferedReader(quotesPath)) {

            String currentLine = readQuotes.readLine();
            while (currentLine != null) {
                quoteFile += currentLine;
                currentLine = readQuotes.readLine();
            }
        }

        Gson quotesParserGson = new Gson();

        Quotes[] quotesArray = quotesParserGson.fromJson(quoteFile, Quotes[].class);

        return quotesArray;
    }

    public static String shuffleQuotes(Quotes[] quotesToShuffle, double inputNumber) {
        int arrayLength = quotesToShuffle.length;
        int randomNum = (int) (inputNumber * arrayLength);

        return quotesToShuffle[randomNum].toString();
    }
}
