/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quote_things;

import com.google.gson.Gson;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class renderQuotes {

    public static void main(String[] args) {

        Path filePath = Paths.get("./assets/quotes.json");

        Quotes[] testQuotesParse = new Quotes[]{};

        try {
            testQuotesParse = parseQuotes(filePath);
        } catch (IOException ex) {
            System.out.println("I could not read these files. Please try again.");
            ex.printStackTrace();
        }

        shuffleQuotes(testQuotesParse);
    }

    public static Quotes[] parseQuotes(Path quotesPath) throws IOException {

        String quoteFile = "";

        try (BufferedReader readQuotes = Files.newBufferedReader(quotesPath)) {

            String currentLine = readQuotes.readLine();
            while (currentLine != null) {
                quoteFile += currentLine;
                currentLine = readQuotes.readLine();
            }
        } catch (IOException ex) {
            throw ex;
        }

        Gson quotesParserGson = new Gson();

        Quotes[] quotesArray = quotesParserGson.fromJson(quoteFile, Quotes[].class);

        return quotesArray;
    }

    public static void shuffleQuotes(Quotes[] quotesToShuffle) {
        int arrayLength = quotesToShuffle.length;
        int randomNum = (int) Math.random() * arrayLength;

        System.out.println(quotesToShuffle[randomNum]);
    }
}
