/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quote_things;

import org.junit.Test;

import static org.junit.Assert.assertNotNull;

public class renderQuotesTest {
    @Test
    public void testAppHasAGreeting() {
        renderQuotes classUnderTest = new renderQuotes();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
