///*
// * This Java source file was generated by the Gradle 'init' task.
// */
//package quote_things;
//
//import org.junit.Test;
//
//import java.io.IOException;
//import java.nio.file.Path;
//import java.nio.file.Paths;
//
//import static org.junit.Assert.*;
//
//public class RenderQuotesTest {
//    @Test
//    public void testQuoteParsing() {
//        Path filePath = Paths.get("./assets/quotes.json");
//
//        Quotes[] testQuotesParse = new Quotes[]{};
//
//        try {
//            testQuotesParse = RenderQuotes.parseQuotes(filePath);
//        } catch (IOException ex) {
//            System.out.println("I could not read these files. Please try again.");
//            ex.printStackTrace();
//        }
//
//        assertEquals("There should be 185 quotes", 185, testQuotesParse.length);
//        assertEquals("Quote #60 should be ", " “来自QQ/微信：996330050的爱*-*\n" +
//                        " -买证★买证件★买波莫纳加州理工大学毕业证\n" +
//                        "tags: 买证-买证件-买波莫纳加州理工大学毕业证\n" +
//                        "0 likes",
//                testQuotesParse[59].toString());
//        assertEquals("Quotes #86 should be an Oliver Bowden quote.", " “While I thought that I was learning how to live, I have been learning how to die.\n" +
//                " -Oliver Bowden\n" +
//                "tags: assassin-s creed da leonardo renaissance vinci\n" +
//                "114 likes", testQuotesParse[85].toString());
//    }
//
//    // Tests should also work when we let the program get the data on its own
//    @Test
//    public void testQuoteAcquisition() {
//
//        Quotes[] quoteList = RenderQuotes.getQuotes("./assets/quotes.json");
//
//        assertEquals("There should be 185 quotes", 185, quoteList.length);
//        assertEquals("Quote #60 should be ", " “来自QQ/微信：996330050的爱*-*\n" +
//                        " -买证★买证件★买波莫纳加州理工大学毕业证\n" +
//                        "tags: 买证-买证件-买波莫纳加州理工大学毕业证\n" +
//                        "0 likes",
//                quoteList[59].toString());
//        assertEquals("Quotes #86 should be an Oliver Bowden quote.", " “While I thought that I was learning how to live, I have been learning how to die.\n" +
//                " -Oliver Bowden\n" +
//                "tags: assassin-s creed da leonardo renaissance vinci\n" +
//                "114 likes", quoteList[85].toString());
//    }
//
//    @Test
//    public void testCorrectQuotes() {
//        Quotes[] quoteList = RenderQuotes.getQuotes("./assets/quotes.json");
//
//        assertEquals("Given 0, method should return the Marilyn Monroe quote.", " “I am good, but not an angel. I do sin, but I am not the devil. I am just a small girl in a big world trying to find someone to love.” \n" +
//                        " -Marilyn Monroe\n" +
//                        "tags: attributed-no-source\n" +
//                        "18651 likes",
//                RenderQuotes.shuffleQuotes(quoteList, 0));
//        assertEquals("Given 0.69, method should return Sartre quote.", " “Hell is—other people!” \n" +
//                        " -Jean-Paul Sartre\n" +
//                        "tags: garcin hell people\n" +
//                        "1717 likes",
//                RenderQuotes.shuffleQuotes(quoteList, 0.69));
//        // Given 1, function should throw and IndexOutOfBoundsException
//        try {
//            RenderQuotes.shuffleQuotes(quoteList, 1);
//            fail("Given 1, function should throw and IndexOutOfBoundsException");
//        } catch (IndexOutOfBoundsException ex) {
//            assertTrue("Given 1, function should throw and IndexOutOfBoundsException", true);
//        }
//    }
//
//
//}
